[build]
  publish = "public"
  command = "npm run build:netlify"
[context.production]
  environment ={  KONTENT_PROJECT_ID = "46a9e64d-4cc9-01ed-3cb5-881e71b1303f", KONTENT_LANGUAGE_CODENAMES = "en-US, cs-CZ" }
[build.environment]
  YARN_VERSION = "1.3.2"
  YARN_FLAGS = "--no-ignore-optional"
[[plugins]]
  package = "netlify-plugin-gatsby-cache"