[build]
  publish = "public"
  command = "npm run build:netlify"
[context.production]
  environment ={  KONTENT_PROJECT_ID = "46a9e64d-4cc9-01ed-3cb5-881e71b1303f", KONTENT_LANGUAGE_CODENAMES = "en-US, cs-CZ", KONTENT_PREVIEW_KEY = "ew0KICAiYWxnIjogIkhTMjU2IiwNCiAgInR5cCI6ICJKV1QiDQp9.ew0KICAianRpIjogIjBlMjdlYjUxYWY0YzQ4NzFiNGM2NWQwOGEwZWViZjU4IiwNCiAgImlhdCI6ICIxNjA4NDYwNTk5IiwNCiAgImV4cCI6ICIxOTU0MDYwNTk5IiwNCiAgInByb2plY3RfaWQiOiAiNDZhOWU2NGQ0Y2M5MDFlZDNjYjU4ODFlNzFiMTMwM2YiLA0KICAidmVyIjogIjEuMC4wIiwNCiAgImF1ZCI6ICJwcmV2aWV3LmRlbGl2ZXIua2VudGljb2Nsb3VkLmNvbSINCn0.5S41xTdVLRtuavp45mVKpydrkAPSZ4JRwEXeewaLyO8", KONTENT_PREVIEW_ENABLED = true}
[build.environment]
  YARN_VERSION = "1.3.2"
  YARN_FLAGS = "--no-ignore-optional"
[[plugins]]
  package = "netlify-plugin-gatsby-cache"